### ISSUE TITLE
数据格式问题

### ISSUE THREAD

**Issue by Acquire2** [goldeneave/NER-Bert-BiLSTM-CRF#1]
你好，我是看了原项目，看到你的问题过来的，我的问题是：在原项目中数据是两类实体识别问题，现在我已经将数据格式修改为处理后数据集格式，那么我需要在哪一块再进行修改，可以实现从 两类实体识别 到 多类实体识别。非常期待你的帮助解答。

**Comment by goldeneave** [comment]
你好，如果确定你的数据已经按照BIO格式处理好，可以替换原位置中的数据，并修改labels为你的数据，直接训练即可

**Comment by Acquire2** [comment]
你好，当我把labels换成六个实体，并将数据处理后，仍然是报错，以下为报错内容，提示json文件解析错误
D:\software\Anaconda3\envs\test2\python.exe D:\software\Anaconda3\bert\TS-BERT-BILSTM-CRF-main\main.py 
['O', 'B-攻击时间', 'I-攻击时间', 'B-目标地区', 'I-目标地区', 'B-目标行业', 'I-目标行业', 'B-攻击目标', 'I-攻击目标', 'B-攻击类型', 'I-攻击类型', 'B-后果', 'I-后果']
{'O': 0, 'B-攻击时间': 1, 'I-攻击时间': 2, 'B-目标地区': 3, 'I-目标地区': 4, 'B-目标行业': 5, 'I-目标行业': 6, 'B-攻击目标': 7, 'I-攻击目标': 8, 'B-攻击类型': 9, 'I-攻击类型': 10, 'B-后果': 11, 'I-后果': 12}
Traceback (most recent call last):
  File "D:\software\Anaconda3\bert\TS-BERT-BILSTM-CRF-main\main.py", line 190, in <module>
    main(data_name)
  File "D:\software\Anaconda3\bert\TS-BERT-BILSTM-CRF-main\main.py", line 149, in main
    train_data = [json.loads(d) for d in train_data]
  File "D:\software\Anaconda3\bert\TS-BERT-BILSTM-CRF-main\main.py", line 149, in <listcomp>
    train_data = [json.loads(d) for d in train_data]
  File "D:\software\Anaconda3\envs\test2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\software\Anaconda3\envs\test2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\software\Anaconda3\envs\test2\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by Acquire2** [comment]
这是我处理后对应的数据示例：

{"id": "AT0002", "text": ["外", "媒", "2", "0", "1", "9", "年", "1", "月", "报", "道", "，", "美", "国", "电", "子", "邮", "件", "商", "V", "F", "E", "m", "a", "i", "l", "发", "现", "有", "黑", "客", "攻", "击", "，", "系", "统", "性", "破", "坏", "了", "公", "司", "的", "服", "务", "硬", "盘", "，", "其", "中", "包", "括", "备", "份", "和", "冗", "余", "。", "该", "公", "司", "的", "员", "工", "目", "前", "正", "在", "努", "力", "恢", "复", "用", "户", "的", "电", "子", "邮", "件", "，", "但", "就", "目", "前", "的", "情", "况", "来", "看", "，", "美", "国", "客", "户", "的", "所", "有", "数", "据", "似", "乎", "都", "被", "永", "久", "删", "除", "。"], "labels": ["O", "O", "B-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "O", "O", "O", "B-目标地区", "I-目标地区", "B-目标行业", "I-目标行业", "I-目标行业", "I-目标行业", "I-目标行业", "B-攻击目标", "I-攻击目标", "I-攻击目标", "I-攻击目标", "I-攻击目标", "I-攻击目标", "I-攻击目标", "O", "O", "O", "B-攻击类型", "I-攻击类型", "I-攻击类型", "I-攻击类型", "O", "O", "O", "O", "B-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}
{"id": "AT0003", "text": ["汽", "车", "巨", "头", "丰", "田", "的", "澳", "洲", "分", "公", "司", "I", "T", "系", "统", "周", "二", "也", "遭", "到", "黑", "客", "攻", "击", "。", "但", "该", "公", "司", "表", "示", "并", "未", "丢", "失", "或", "外", "泄", "任", "何", "数", "据", "。", "2", "0", "1", "9", "年", "1", "月", "，", "丰", "田", "澳", "洲", "分", "公", "司", "表", "示", "，", "目", "前", "还", "不", "知", "道", "攻", "击", "来", "源", "，", "但", "黑", "客", "造", "成", "的", "威", "胁", "已", "在", "该", "公", "司", "I", "T", "部", "门", "的", "控", "制", "之", "下", "。", "“", "目", "前", "，", "我", "们", "相", "信", "雇", "员", "的", "私", "人", "信", "息", "或", "者", "客", "户", "的", "数", "据", "，", "并", "没", "有", "被", "暴", "露", "。", "”"], "labels": ["B-目标行业", "I-目标行业", "O", "O", "B-攻击目标", "I-攻击目标", "O", "B-目标地区", "I-目标地区", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-攻击类型", "I-攻击类型", "I-攻击类型", "I-攻击类型", "O", "O", "O", "O", "O", "O", "O", "O", "B-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "I-后果", "O", "B-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "I-攻击时间", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}

**Comment by goldeneave** [comment]
数据末尾可能有换行符 把两个文件最后的换行符删掉试一下

**Comment by Acquire2** [comment]
非常感谢你，我再试试
